"""
Django settings for enac project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os, dj_database_url
from pathlib import Path
import cloudinary


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-8e2_#uqa^+*nd1kx^#fpmk3_0@@u8bw0)k*nyse7ff+loukee+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'accounts',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'payment.apps.PaymentConfig',
    'ecommerce',
    'cart',
    'wishlist',
    'django.contrib.humanize',
    'storages',
    'pwa',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'enac.urls'

AUTH_USER_MODEL = 'ecommerce.User'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'cart.context_processors.cart',
                'cart.context_processors.cart_items',
                'wishlist.context_processors.wishlist',
                'wishlist.context_processors.wishlist_items',
                'ecommerce.context_processors.schools_listed',
                'ecommerce.context_processors.schools_fulllist',
                'ecommerce.context_processors.all_schools',
            ],
        },
    },
]

WSGI_APPLICATION = 'enac.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


database_url = "postgresql://enac_user:wHfQTZCX9z2nB2oBUhYVDHQ5UJYuhbhf@dpg-d2ci7l8gjchc7385bm30-a.oregon-postgres.render.com/enac"

DATABASES = {
    "default": dj_database_url.parse(database_url)
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

AWS_ACCESS_KEY_ID = 'AKIA2UC27BOKK6HXXAM4'
AWS_SECRET_ACCESS_KEY = '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'
AWS_STORAGE_BUCKET_NAME = 'enacs3'
AWS_S3_REGION_NAME = 'eu-north-1'
AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com'
AWS_DEFAULT_ACL = 'public-read'
AWS_S3_FILE_OVERWRITE = False


STATIC_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/static/'

# STATIC_URL = "https://vercel-static-hrgfww1d7-samcodios-projects.vercel.app/static/"

# STATIC_URL = 'static/'

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)

STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# default storage cloundinary
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': 'dsmr339pe',
    'API_KEY': '662555225263383',
    'API_SECRET': 'FTOjuN0g_hw5G7znJ1A0H1CBdA0',
    'auto_create_folders': True,
    'auto_optimize': True,  # Enable automatic image optimization
    'auto_responsive': True,  # Enable automatic image resizing
}


cloudinary.config(
    cloud_name='dtgepccth',
    api_key='363466449134293',
    api_secret='biHImhWRz0fsh_sOgrlJqS1I5mg',
)

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'earlynestagencycompany@gmail.com'
EMAIL_HOST_PASSWORD = 'hhxf wtir kodx mwow'
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False


DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

CART_MAX_DISPLAY_ITEMS = 3

PAYSTACK_SECRET_KEY = "sk_test_d64896d291b301095632f4f529af352de7573a60"
# PAYSTACK_SECRET_KEY = "sk_live_633032dee43d6526e7ef637f094abc222cc9ec8a"


PWA_APP_NAME = 'ENAC'
PWA_APP_DESCRIPTION = "Early Nest Agency Company"
PWA_APP_THEME_COLOR = '#000000'
PWA_APP_BACKGROUND_COLOR = '#ffffff'
PWA_APP_DISPLAY = 'standalone'
PWA_APP_SCOPE = '/'
PWA_APP_ORIENTATION = 'portrait'
PWA_APP_START_URL = '/'
PWA_APP_ICONS = [
    {
        'src': '/static/assets/images/enac_logo.png',
        'sizes': '512x512'
    },
    {
        'src': '/static/assets/images/enac_logo.png',
        'sizes': '192x192'
    }
]
PWA_APP_DIR = 'ltr'
PWA_APP_LANG = 'en-US'






