# Generated by Django 5.2.1 on 2025-05-29 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lodge_name', models.CharField(max_length=100)),
                ('lodge_img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('lodge_img2', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('lodge_img3', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('lodge_video', models.FileField(blank=True, help_text='Upload a video file', null=True, upload_to='videos/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('posted_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('sale', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school', to='ecommerce.school')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('phone_num', models.CharField(blank=True, max_length=12, null=True)),
                ('phone_num2', models.CharField(blank=True, max_length=12, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('old_cart', models.CharField(blank=True, max_length=1000, null=True)),
                ('old_wishlist', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mute', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='norm_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
