# Generated by Django 5.2.1 on 2025-05-29 15:39

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stay_period',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='lodge_img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='lodge_img2',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='lodge_img3',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='lodge_video',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload a video file', max_length=255, null=True),
        ),
    ]
