# Generated by Django 5.2.1 on 2025-05-29 21:01

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_product_stay_period_alter_product_lodge_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='school_logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
