# Generated by Django 5.2.1 on 2025-05-29 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_school_school_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='short_verion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_name',
            field=models.CharField(max_length=255),
        ),
    ]
