# Generated by Django 5.2.1 on 2025-05-29 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_school_short_verion_alter_school_school_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='short_verion',
            new_name='short_version',
        ),
    ]
