# Generated by Django 5.2.1 on 2025-06-13 21:54

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_product_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['school_name']},
        ),
        migrations.AddField(
            model_name='product',
            name='lessor_img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='product',
            name='roommate',
            field=models.BooleanField(default=True),
        ),
    ]
