# Generated by Django 5.2.1 on 2025-06-13 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_alter_school_options_product_lessor_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='roommate',
            field=models.BooleanField(default=False),
        ),
    ]
