# Generated by Django 5.2.1 on 2025-06-13 22:18

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_alter_product_roommate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='lessor_img',
        ),
        migrations.AddField(
            model_name='product',
            name='lodge_img4',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
