# Generated by Django 5.2.1 on 2025-06-15 21:25

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_remove_product_lessor_img_product_lodge_img4'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='lessor_proof',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
