# Generated by Django 5.2.1 on 2025-06-22 11:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0014_product_approved_alter_product_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rm_user',
            field=models.ManyToManyField(blank=True, related_name='requesters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='paidUsers', to=settings.AUTH_USER_MODEL),
        ),
    ]
