# Generated by Django 5.2.1 on 2025-06-24 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0017_remove_product_approved_product_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='caretaker',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
