# Generated by Django 5.2.1 on 2025-06-26 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0018_product_address_product_caretaker'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='light',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='stable_water',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='tiled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='upstairs',
            field=models.BooleanField(default=False),
        ),
    ]
