# Generated by Django 5.2.1 on 2025-07-14 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0019_product_light_product_stable_water_product_tiled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='level',
            field=models.CharField(blank=True, choices=[('100', '100 Level'), ('200', '200 Level'), ('300', '300 Level'), ('400', '400 Level'), ('500', '500 Level'), ('600', '600 Level')], max_length=255, null=True),
        ),
    ]
