# Generated by Django 5.2.1 on 2025-07-28 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0020_product_department_product_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='room_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
